# Generated by Django 5.1.6 on 2026-03-15 18:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='codigo_qr',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
