# Generated by Django 6.0.3 on 2026-03-17 15:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioTiquetes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField(default=django.utils.timezone.now)),
                ('cantidad_inicial', models.PositiveIntegerField()),
                ('cantidad_disponible', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Inventarios de Tiquetes',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FoodCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('empleados', models.ManyToManyField(blank=True, related_name='calendarios_asignados', to='accounts.empleado')),
                ('items', models.ManyToManyField(related_name='calendarios', to='schedule.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pagado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('comprobante', models.CharField(blank=True, help_text='Referencia o link al comprobante', max_length=255)),
                ('validado_por_gh', models.BooleanField(default=False)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_registrados', to='accounts.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudTiquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tiquete', models.CharField(choices=[('fisico', 'Físico'), ('qr', 'Código QR')], max_length=20)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('fecha_reclamo', models.DateField(blank=True, null=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_tiquete', to='accounts.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumoAlmuerzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('hora_registro', models.DateTimeField(auto_now_add=True)),
                ('valor_almuerzo', models.DecimalField(decimal_places=2, default=15000.0, max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos_almuerzo', to='accounts.empleado')),
            ],
            options={
                'unique_together': {('empleado', 'fecha')},
            },
        ),
    ]
