# Generated by Django 5.1.6 on 2026-03-15 18:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_empleado_codigo_qr'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoAlmuerzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('hora_registro', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos_almuerzo', to='accounts.empleado')),
            ],
            options={
                'unique_together': {('empleado', 'fecha')},
            },
        ),
    ]
