# Generated by Django 6.0.3 on 2026-03-23 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comidareservada',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.empleado'),
        ),
        migrations.AddField(
            model_name='comidareservada',
            name='comida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.comida'),
        ),
        migrations.AddField(
            model_name='consumo',
            name='comida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.comidareservada'),
        ),
        migrations.AddField(
            model_name='registropago',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_registrados', to='users.empleado'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='comida',
            field=models.ManyToManyField(blank=True, to='schedule.comidareservada'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.empleado'),
        ),
        migrations.AddField(
            model_name='solicitudtiquete',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_tiquete', to='users.empleado'),
        ),
        migrations.AlterUniqueTogether(
            name='consumo',
            unique_together={('comida',)},
        ),
    ]
