# Generated by Django 6.0.3 on 2026-03-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariotiquetes',
            name='max_tiquetes_por_empleado',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
