# Generated by Django 5.1.6 on 2026-03-15 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_empleado_codigo_qr'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudTiquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tiquete', models.CharField(choices=[('fisico', 'Físico'), ('qr', 'Código QR')], max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_tiquete', to='accounts.empleado')),
            ],
        ),
    ]
