# Generated by Django 6.0.3 on 2026-03-24 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_initial'),
        ('users', '0003_allow_blank_numero_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comidareservada',
            name='comida',
        ),
        migrations.RemoveField(
            model_name='comidareservada',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='comida',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='empleado',
        ),
        migrations.AlterUniqueTogether(
            name='consumo',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='consumo',
            name='empleado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.empleado'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Almuerzo',
        ),
        migrations.DeleteModel(
            name='Comida',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.RemoveField(
            model_name='consumo',
            name='comida',
        ),
        migrations.DeleteModel(
            name='ComidaReservada',
        ),
    ]
