# Generated by Django 6.0.3 on 2026-03-17 19:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('schedule', '0002_inventariotiquetes_max_tiquetes_por_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tiquete',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consumido', models.BooleanField(default=False)),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('fecha_consumo', models.DateTimeField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiquetes_individuales', to='accounts.empleado')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiquetes_generados', to='schedule.solicitudtiquete')),
            ],
        ),
    ]
