# Generated by Django 5.1.6 on 2026-03-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_solicitudtiquete'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumoalmuerzo',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consumoalmuerzo',
            name='valor_almuerzo',
            field=models.DecimalField(decimal_places=2, default=15000.0, max_digits=10),
        ),
    ]
