# Generated by Django 6.0.3 on 2026-04-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_remove_comidareservada_comida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registropago',
            name='confirmado_por_empleado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='solicitudtiquete',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
