# Generated by Django 6.0.3 on 2026-03-18 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_tiquete'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tiquete',
        ),
    ]
