# Generated by Django 6.0.3 on 2026-03-19 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_delete_tiquete'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariotiquetes',
            name='precio_tiquete',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=10),
        ),
    ]
