# Generated by Django 6.0.3 on 2026-04-19 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_registropago_confirmado_por_empleado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_edicion', models.DateTimeField(auto_now_add=True)),
                ('campo', models.CharField(max_length=50)),
                ('valor_anterior', models.CharField(max_length=255)),
                ('valor_nuevo', models.CharField(max_length=255)),
                ('motivo', models.TextField(blank=True)),
                ('consumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='schedule.consumo')),
                ('editado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ediciones_consumo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de consumo',
                'verbose_name_plural': 'Logs de consumo',
                'ordering': ['-fecha_edicion'],
            },
        ),
    ]
