# Generated by Django 6.0.3 on 2026-03-20 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_inventariotiquetes_precio_tiquete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumoalmuerzo',
            name='valor_almuerzo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
