# Generated by Django 6.0.3 on 2026-03-20 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_alter_consumoalmuerzo_valor_almuerzo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudtiquete',
            name='tipo_tiquete',
        ),
    ]
