# Generated by Django 6.0.3 on 2026-03-20 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_remove_solicitudtiquete_tipo_tiquete'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodCalendar',
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
