# Generated by Django 6.0.3 on 2026-03-20 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_delete_foodcalendar_delete_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudtiquete',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=10),
        ),
    ]
