CREATE USER p2usr WITH PASSWORD 'proyecto_2_psw';
CREATE DATABASE IF NOT EXISTS lunchflow;
GRANT ALL PRIVILEGES ON DATABASE lunchflow TO p2usr;
GRANT CONNECT ON DATABASE lunchflow TO p2usr;
GRANT USAGE, CREATE ON SCHEMA public TO p2usr;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO p2usr;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO p2usr;