name: Run tests

on:
  pull_request:
    branches:
      - EGS3D-branch # Recordar quitar esta mamada despues por main

  push:
    branches:
      - EGS3D-branch

  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Start containers
        run: docker compose up -d

      - name: Run tests
        run: docker compose exec web python manage.py test